[package]
name = "puzterm"
version = "0.2.1"
authors = ["rparrett <robparrett@gmail.com>"]

[dependencies]
encoding = "0.2.33"
termion = "^1.5"
stopwatch = "0.0.7"

[dependencies.nom]
version = "^5.0"
